### ISSUE TITLE
ValueError: Unknown status message: u'EXPORTED'

### ISSUE THREAD

**Issue by HLFH** [letoams/hash-slinger#15]
Hi,

OPENPKGKEY RR is generated but it seems I have a small issue/warning.

```
[hlfh@arch-server ~]$ openpgpkey --output rfc user@example.com
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/gnupg.py", line 753, in _read_response
    result.handle_status(keyword, value)
  File "/usr/lib/python2.7/site-packages/gnupg.py", line 579, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'EXPORTED'

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/gnupg.py", line 753, in _read_response
    result.handle_status(keyword, value)
  File "/usr/lib/python2.7/site-packages/gnupg.py", line 579, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'EXPORTED'
```

**Comment by HLFH** [comment]
EDIT: [python2-gnupg dependency is out-of-date](https://aur.archlinux.org/packages/python2-gnupg/).

EDIT2: I still get the issue on the master branch of python2-gnupg. https://bitbucket.org/vinay.sajip/python-gnupg/

**Comment by HLFH** [comment]
I'll create the issue on python2-gnupg.
