### ISSUE TITLE
Replace M2Crypto

### ISSUE THREAD

**Issue by bgermann** [letoams/hash-slinger#49]
Please replace M2Crypto. It is now in maintainance mode and the project officially recommends [cryptography](https://cryptography.io).

**Comment by frankcrawford** [comment]
This is going to be an issue for the Fedora package as well, as m2crypto it has been orphaned, and will be dropped for a future release (probably F42).  That will cause hash-slinger to fail to build, and hence will not be available.

**Comment by paulwouters** [comment]
PR's are welcome. I personally do not have the resources to work on this.

**Comment by stoecker** [comment]
Same for me. I'd only go for that change when SUSE drops m2crpyto, so that may be some time. I'd help with an PR in case of problems, but currently won't spent the time to do that change myself.

**Comment by frankcrawford** [comment]
Just as a note for rawhide (F42) now lists hash-slinger as fail to build.

**Comment by onny** [comment]
Stopped working on NixOS too

**Comment by frankcrawford** [comment]
Any updates on this, otherwise for Fedora I'm going to knock out `tlsa` as I think it is the only function using `m2crypto`.

**Comment by stoecker** [comment]
OTOH tlsa is also the most important...

**Comment by frankcrawford** [comment]
Arguably, yes, although currently it won't install on a number of OS and no one looks to be willing to fix the issue.

Unfortunately, I'm a packager not really a programmer so don't really know what to do for a fix.

**Comment by stoecker** [comment]
What about a patch which will issue a warning like "tlsa needs to change m2crypto to crypthography" when the tool is called?

```
diff --git a/tlsa b/tlsa
index 18bf424..274dc3e 100755
--- a/tlsa
+++ b/tlsa
@@ -31,7 +31,12 @@ import socket
 import unbound
 import subprocess
 import re
-from M2Crypto import X509, SSL, BIO, m2
+try:
+  from M2Crypto import X509, SSL, BIO, m2
+except:
+  print('The tlsa tool needs to change m2crypto to crypthography to work again')
+  exit(20)
+
 from binascii import b2a_hex
 from hashlib import sha256, sha512
 from ipaddress import IPv4Address, IPv6Address
```

**Comment by frankcrawford** [comment]
Haa, that was almost exactly what I was planning to add, although it doesn't really help it get fixed.  At least it with some right packaging efforts, it will at least allow it to install.

**Comment by paulwouters** [comment]
not sure that is useful. I will see about getting it fixed.

**Comment by onny** [comment]
This is one error I'm getting on NixOS now

``` 
onny@nixos ~/p/nixpkgs (master)> ./result/bin/tlsa --create --selector 1 --protocol tcp -p 25 --create mx1.project-insanity.org
Traceback (most recent call last):
  File "/nix/store/c38gmg0ab8hyxqskk4919ij3gylmh2zi-hash-slinger-3.4/bin/.tlsa-wrapped", line 874, in <module>
    sslStartTLSConnect(connection, (str(address), int(connection_port)), args.starttls)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c38gmg0ab8hyxqskk4919ij3gylmh2zi-hash-slinger-3.4/bin/.tlsa-wrapped", line 252, in sslStartTLSConnect
    ret = connection.connect_ssl()
  File "/nix/store/ls5zcyv3f7ih07aswrrnmfcl2m8hbs48-python3.13-m2crypto-0.45.0/lib/python3.13/site-packages/M2Crypto/SSL/Connection.py", line 320, in connect_ssl
    return m2.ssl_connect(self.ssl, self._timeout)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
M2Crypto.SSL.SSLError: wrong version number
```

**Comment by hgshoggins** [comment]
You all probably already saw this, but there are migration notes on how to navigate from M2Crypto to PyCA/cryptography: https://m2crypto.readthedocs.io/en/latest/howto.migration.html. 
Would that be useful?

(for the record, M2Crypto now refuses to install _via_ `pip` on Fedora 43)
